name: Update Curated Mod List

on:
  schedule:
    - cron: '0 * * * *' # Runs at the beginning of every hour
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Step 1: Check out the repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up the Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Run script
      - name: Generate curated_list.json
        run: node .github/scripts/generate_curated_list.cjs
        env:
          NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}

      # Step 4: Automatically commit the newly generated file back to the repository
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Auto-update curated mod list"
          file_pattern: curated/curated_list.json # Only commit if this specific file changes
